### ISSUE TITLE
Is the checkpoint provided the same as the one in the paper?

### ISSUE THREAD

**Issue by bainjamain** [owenzlz/PA4Inpaint#1]
Hey!
Is the checkpoint provided in `download_checkpoints.sh` the same as the one used in the paper? I'm getting underwhelming results when playing with it with a lot of false positives.
Thanks!

**Comment by owenzlz** [comment]
Yes, this checkpoint is the one we used in the paper. I am wondering what methods did you use to generate the test images. The checkpoint should have reasonably good performance on LaMa-like inpainting outputs, but we also observed its current state might have more false positive when testing on very different methods.
