### ISSUE TITLE
How to download the dataset and the checkpoints? Always access denied here

### ISSUE THREAD

**Issue by wuhang03** [owenzlz/PA4Inpaint#3]
After installing the gdown, when I try to run the cmd, it keeps telling me as follows:
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to chang
        the permission to 'Anyone with the link', or have had many accesse

You may still be able to access the file from the browser:

         https://drive.google.com/uc?id=1O1m5WpJhW6_l4Dm3v70hW1297zoAnpRQ

I just have no idea how to solve this issue, I'd appreciate it much if you can give me a hand here!

**Comment by Drangonliao123** [comment]
> ```
>      https://drive.google.com/uc?id=1O1m5WpJhW6_l4Dm3v70hW1297zoAnpRQ
> ```

Have you solved your problem yet?

**Comment by aakritd** [comment]
hello the link isnt working. Can you fix it?

**Comment by gyfastas** [comment]
The link is unavailable. Is it able to update the link?

**Comment by owenzlz** [comment]
Hi, my email account was disabled. Sorry for the delay! The data link has been updated. Alternatively, more data can be downloaded in this github: [https://github.com/owenzlz/PAL4VST](https://github.com/owenzlz/PAL4VST)
